support recaptcha v3
CruGlobal/campaign-forms pull request #64
Opened 2020-10-20 18:47 UTC by andrewroth

2020-10-20 20:00 UTC, knutsenm requested changes

2020-10-20 20:04 UTC, andrewroth commented on app/admin/form.rb
> +    :use_recaptcha, :recaptcha_key, :recaptcha_secret, :recaptcha_v3, :origin,
Not easily.  I've tried to customize active admin like that (since there's no built-in way to do it) and it's not easy to do, but possible.  Not worth it here imo.  Adding a validation is straightforward and works well enough.

2020-10-20 20:05 UTC, andrewroth commented on app/views/admin/forms/_form.html.erb
> +<%= javascript_pack_tag form.recaptcha_v3 ? 'campaign-v3' : 'campaign' %>
Yeah ok, I agree

2020-10-20 20:05 UTC, andrewroth commented on app/models/form.rb
> +    if recaptcha_v3 && use_recaptcha
Good catch, was going to write a test for this as well

2020-10-21 16:19 UTC, OzzieOrca approved these changes

2020-10-21 16:19 UTC, OzzieOrca commented on app/javascript/campaign-form-v3.js
> +                  page: {pageInfo: {emailList: 'ACS | ' + data.campaign_codes.join(' | ')}}
You could use template literals
```suggestion
                  page: { pageInfo: { emailList: `ACS | ${data.campaign_codes.join(' | ')}` } }
```

2020-10-21 16:19 UTC, OzzieOrca commented on app/javascript/campaign-form-v3.js
> +                window.digitalData = $.extend(true, {}, window.digitalData || {}, {
I was going to suggest the ES6 spread operator for this but maybe it's doing a deep merge (which is still possible but you'd have to spread at every level).

2020-10-21 16:33 UTC, knutsenm requested changes

2020-10-21 16:33 UTC, knutsenm commented on app/javascript/campaign-form-v3.js
> +              gecaptcha
Missing `r`; is that a typo?

2020-10-22 16:51 UTC, andrewroth commented on app/javascript/campaign-form-v3.js
> +                  page: {pageInfo: {emailList: 'ACS | ' + data.campaign_codes.join(' | ')}}
This is a copy of campaign.js, is it worth doing this in both files?  @knutsenm what do you think?

2020-11-05 17:09 UTC, merged