AC-17, support recaptcha v3 and v2 in a single js file
CruGlobal/campaign-forms pull request #65
Opened 2020-10-23 21:57 UTC by andrewroth

Assuming you prefer this merged version, it would replace #64

2020-10-26 19:27 UTC, OzzieOrca requested changes
JS code looks fine. You've got a bunch of `debugger` and `console.log` statements and comments in there still that should be cleaned up.

2020-10-27 21:09 UTC, knutsenm requested changes

2020-10-27 21:09 UTC, knutsenm commented on app/admin/form.rb
> +      f.input :recaptcha_v3_threshold, hint: "1.0 is very likely a good interaction, 0.0 is very likely a bot. Only submissions higher than this value will be accepted."
Should this be "equal to or higher than"? If so, it might be easier to say "Submissions less than this value will be rejected."

2020-10-27 21:09 UTC, knutsenm commented on app/javascript/campaign-form.js
> +    /* test */
Omit?

2020-10-27 21:09 UTC, knutsenm commented on app/models/form.rb
> +  def recaptcha_v3_required_for_v3_threshold
This validation may not be necessary. If it is, there has to be a way for the admin to toggle back to v2.

2020-10-27 21:09 UTC, knutsenm commented on app/models/recaptcha.rb
> +      return form.recaptcha_v3 ? json["score"] > form.recaptcha_v3_threshold : true
Should this be `>=`, just in case score and threshold are both zero?

2020-10-28 14:11 UTC, andrewroth commented on app/models/form.rb
> +  def recaptcha_v3_required_for_v3_threshold
Yeah, they'd have to blank it out to go back to v2.  May be the case adding more hoops to jump through discourages people from using v2, but perhaps also not our job.  I'm fine with removing this one.

2020-10-28 14:40 UTC, knutsenm requested changes

2020-10-28 14:40 UTC, knutsenm commented on db/schema.rb
> +    t.boolean "persist", default: false
Where did this come from?

2020-10-29 16:39 UTC, OzzieOrca approved these changes
You could use `const` a lot more but JS looks good.

2020-10-29 16:39 UTC, OzzieOrca commented on app/javascript/campaign-form.js
> +        }
```suggestion
        const data = campaignForms[formId].v3
          ? { "g-recaptcha-response": recaptchaToken }
          : {};
```

2020-10-29 16:39 UTC, OzzieOrca commented on app/javascript/campaign-form.js
> +          var $form = $(form);
```suggestion
          const $form = $(form);
```

2020-10-29 16:39 UTC, OzzieOrca commented on app/javascript/campaign-form.js
> +          var formId = $form.attr('id')
```suggestion
          const formId = $form.attr('id')
```

2020-10-29 16:39 UTC, OzzieOrca commented on app/javascript/campaign-form.js
> +            var recaptchaDiv = $('div[data-sitekey]', form)[0]
```suggestion
            const recaptchaDiv = $('div[data-sitekey]', form)[0];
```

2020-10-29 18:51 UTC, OzzieOrca approved these changes

2020-11-03 21:19 UTC, knutsenm commented
Rubocop is unhappy

2020-11-05 17:09 UTC, merged